[workspace]
authors = ["stevenhirsch <stevehirsch94@gmail.com>"]
channels = ["conda-forge"]
name = "test_marimo_gh_pages"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
marimo = ">=0.19.8,<0.20"
numpy = ">=2.4.2,<3"
pandas = ">=3.0.0,<4"
matplotlib = ">=3.10.8,<4"
